# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'parking_form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QFormLayout, QGridLayout,
    QLayout, QPushButton, QSizePolicy, QSpacerItem,
    QTextEdit, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(792, 743)
        Widget.setMouseTracking(False)
        Widget.setTabletTracking(False)
        Widget.setAutoFillBackground(False)
        self.formLayoutWidget = QWidget(Widget)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(70, 30, 239, 685))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setVerticalSpacing(7)
        self.carSpot_1 = QPushButton(self.formLayoutWidget)
        self.carSpot_1.setObjectName(u"carSpot_1")
        self.carSpot_1.setEnabled(True)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush1 = QBrush(QColor(170, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush1)
        brush2 = QBrush(QColor(255, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_1.setPalette(palette)
        self.carSpot_1.setMouseTracking(False)
        self.carSpot_1.setAutoFillBackground(False)
        self.carSpot_1.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        icon = QIcon()
        icon.addFile(u"../car.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.carSpot_1.setIcon(icon)
        self.carSpot_1.setIconSize(QSize(100, 100))
        self.carSpot_1.setCheckable(True)
        self.carSpot_1.setChecked(False)
        self.carSpot_1.setAutoExclusive(False)
        self.carSpot_1.setAutoDefault(False)
        self.carSpot_1.setFlat(False)

        self.gridLayout.addWidget(self.carSpot_1, 0, 0, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_2, 4, 0, 1, 1)

        self.carSpot_5 = QPushButton(self.formLayoutWidget)
        self.carSpot_5.setObjectName(u"carSpot_5")
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Button, brush)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_5.setPalette(palette1)
        self.carSpot_5.setMouseTracking(False)
        self.carSpot_5.setAutoFillBackground(False)
        self.carSpot_5.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_5.setIcon(icon)
        self.carSpot_5.setIconSize(QSize(100, 100))
        self.carSpot_5.setCheckable(True)
        self.carSpot_5.setChecked(False)
        self.carSpot_5.setAutoExclusive(False)
        self.carSpot_5.setAutoDefault(False)
        self.carSpot_5.setFlat(False)

        self.gridLayout.addWidget(self.carSpot_5, 9, 0, 1, 1)

        self.carSpot_3 = QPushButton(self.formLayoutWidget)
        self.carSpot_3.setObjectName(u"carSpot_3")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush)
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_3.setPalette(palette2)
        self.carSpot_3.setMouseTracking(False)
        self.carSpot_3.setAutoFillBackground(False)
        self.carSpot_3.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_3.setIcon(icon)
        self.carSpot_3.setIconSize(QSize(100, 100))
        self.carSpot_3.setCheckable(True)
        self.carSpot_3.setChecked(False)
        self.carSpot_3.setAutoExclusive(False)
        self.carSpot_3.setAutoDefault(False)
        self.carSpot_3.setFlat(False)

        self.gridLayout.addWidget(self.carSpot_3, 5, 0, 1, 1)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_3, 8, 0, 1, 1)

        self.carSpot_4 = QPushButton(self.formLayoutWidget)
        self.carSpot_4.setObjectName(u"carSpot_4")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush)
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_4.setPalette(palette3)
        self.carSpot_4.setMouseTracking(False)
        self.carSpot_4.setAutoFillBackground(False)
        self.carSpot_4.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_4.setIcon(icon)
        self.carSpot_4.setIconSize(QSize(100, 100))
        self.carSpot_4.setCheckable(True)
        self.carSpot_4.setChecked(False)
        self.carSpot_4.setAutoExclusive(False)
        self.carSpot_4.setAutoDefault(False)
        self.carSpot_4.setFlat(False)

        self.gridLayout.addWidget(self.carSpot_4, 7, 0, 1, 1)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer_5, 6, 0, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer, 2, 0, 1, 1)

        self.carSpot_2 = QPushButton(self.formLayoutWidget)
        self.carSpot_2.setObjectName(u"carSpot_2")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Button, brush)
        palette4.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_2.setPalette(palette4)
        self.carSpot_2.setMouseTracking(False)
        self.carSpot_2.setAutoFillBackground(False)
        self.carSpot_2.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_2.setIcon(icon)
        self.carSpot_2.setIconSize(QSize(100, 100))
        self.carSpot_2.setCheckable(True)
        self.carSpot_2.setChecked(False)
        self.carSpot_2.setAutoExclusive(False)
        self.carSpot_2.setAutoDefault(False)
        self.carSpot_2.setFlat(False)

        self.gridLayout.addWidget(self.carSpot_2, 3, 0, 1, 1)


        self.formLayout.setLayout(0, QFormLayout.LabelRole, self.gridLayout)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_7, 8, 0, 1, 1)

        self.carSpot_6 = QPushButton(self.formLayoutWidget)
        self.carSpot_6.setObjectName(u"carSpot_6")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Button, brush)
        palette5.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_6.setPalette(palette5)
        self.carSpot_6.setMouseTracking(False)
        self.carSpot_6.setAutoFillBackground(False)
        self.carSpot_6.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_6.setIcon(icon)
        self.carSpot_6.setIconSize(QSize(100, 100))
        self.carSpot_6.setCheckable(True)
        self.carSpot_6.setChecked(False)
        self.carSpot_6.setAutoExclusive(False)
        self.carSpot_6.setAutoDefault(False)
        self.carSpot_6.setFlat(False)

        self.gridLayout_2.addWidget(self.carSpot_6, 5, 0, 1, 1)

        self.carSpot_10 = QPushButton(self.formLayoutWidget)
        self.carSpot_10.setObjectName(u"carSpot_10")
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Button, brush)
        palette6.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_10.setPalette(palette6)
        self.carSpot_10.setMouseTracking(False)
        self.carSpot_10.setAutoFillBackground(False)
        self.carSpot_10.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_10.setIcon(icon)
        self.carSpot_10.setIconSize(QSize(100, 100))
        self.carSpot_10.setCheckable(True)
        self.carSpot_10.setChecked(False)
        self.carSpot_10.setAutoExclusive(False)
        self.carSpot_10.setAutoDefault(False)
        self.carSpot_10.setFlat(False)

        self.gridLayout_2.addWidget(self.carSpot_10, 7, 0, 1, 1)

        self.horizontalSpacer_10 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_10, 6, 0, 1, 1)

        self.carSpot_7 = QPushButton(self.formLayoutWidget)
        self.carSpot_7.setObjectName(u"carSpot_7")
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Button, brush)
        palette7.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_7.setPalette(palette7)
        self.carSpot_7.setMouseTracking(False)
        self.carSpot_7.setAutoFillBackground(False)
        self.carSpot_7.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_7.setIcon(icon)
        self.carSpot_7.setIconSize(QSize(100, 100))
        self.carSpot_7.setCheckable(True)
        self.carSpot_7.setChecked(False)
        self.carSpot_7.setAutoExclusive(False)
        self.carSpot_7.setAutoDefault(False)
        self.carSpot_7.setFlat(False)

        self.gridLayout_2.addWidget(self.carSpot_7, 3, 0, 1, 1)

        self.carSpot_8 = QPushButton(self.formLayoutWidget)
        self.carSpot_8.setObjectName(u"carSpot_8")
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Button, brush)
        palette8.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_8.setPalette(palette8)
        self.carSpot_8.setMouseTracking(False)
        self.carSpot_8.setAutoFillBackground(False)
        self.carSpot_8.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_8.setIcon(icon)
        self.carSpot_8.setIconSize(QSize(100, 100))
        self.carSpot_8.setCheckable(True)
        self.carSpot_8.setChecked(False)
        self.carSpot_8.setAutoExclusive(False)
        self.carSpot_8.setAutoDefault(False)
        self.carSpot_8.setFlat(False)

        self.gridLayout_2.addWidget(self.carSpot_8, 9, 0, 1, 1)

        self.horizontalSpacer_8 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_8, 2, 0, 1, 1)

        self.horizontalSpacer_9 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_9, 4, 0, 1, 1)

        self.carSpot_9 = QPushButton(self.formLayoutWidget)
        self.carSpot_9.setObjectName(u"carSpot_9")
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush)
        palette9.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_9.setPalette(palette9)
        self.carSpot_9.setMouseTracking(False)
        self.carSpot_9.setAutoFillBackground(False)
        self.carSpot_9.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_9.setIcon(icon)
        self.carSpot_9.setIconSize(QSize(100, 100))
        self.carSpot_9.setCheckable(True)
        self.carSpot_9.setChecked(False)
        self.carSpot_9.setAutoExclusive(False)
        self.carSpot_9.setAutoDefault(False)
        self.carSpot_9.setFlat(False)

        self.gridLayout_2.addWidget(self.carSpot_9, 1, 0, 1, 1)


        self.formLayout.setLayout(0, QFormLayout.FieldRole, self.gridLayout_2)

        self.formLayoutWidget_2 = QWidget(Widget)
        self.formLayoutWidget_2.setObjectName(u"formLayoutWidget_2")
        self.formLayoutWidget_2.setGeometry(QRect(520, 100, 199, 585))
        self.formLayout_2 = QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetFixedSize)
        self.horizontalSpacer_12 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_3.addItem(self.horizontalSpacer_12, 3, 0, 1, 1)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_3.addItem(self.horizontalSpacer_4, 7, 0, 1, 1)

        self.horizontalSpacer_11 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_3.addItem(self.horizontalSpacer_11, 1, 0, 1, 1)

        self.carSpot_15 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_15.setObjectName(u"carSpot_15")
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush)
        palette10.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_15.setPalette(palette10)
        self.carSpot_15.setMouseTracking(False)
        self.carSpot_15.setAutoFillBackground(False)
        self.carSpot_15.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u"../motorcycle.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.carSpot_15.setIcon(icon1)
        self.carSpot_15.setIconSize(QSize(80, 80))
        self.carSpot_15.setCheckable(True)
        self.carSpot_15.setChecked(False)
        self.carSpot_15.setAutoExclusive(False)
        self.carSpot_15.setAutoDefault(False)
        self.carSpot_15.setFlat(False)

        self.gridLayout_3.addWidget(self.carSpot_15, 6, 0, 1, 1)

        self.carSpot_14 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_14.setObjectName(u"carSpot_14")
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Button, brush)
        palette11.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_14.setPalette(palette11)
        self.carSpot_14.setMouseTracking(False)
        self.carSpot_14.setAutoFillBackground(False)
        self.carSpot_14.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_14.setIcon(icon1)
        self.carSpot_14.setIconSize(QSize(80, 80))
        self.carSpot_14.setCheckable(True)
        self.carSpot_14.setChecked(False)
        self.carSpot_14.setAutoExclusive(False)
        self.carSpot_14.setAutoDefault(False)
        self.carSpot_14.setFlat(False)

        self.gridLayout_3.addWidget(self.carSpot_14, 0, 0, 1, 1)

        self.carSpot_13 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_13.setObjectName(u"carSpot_13")
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Button, brush)
        palette12.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_13.setPalette(palette12)
        self.carSpot_13.setMouseTracking(False)
        self.carSpot_13.setAutoFillBackground(False)
        self.carSpot_13.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_13.setIcon(icon1)
        self.carSpot_13.setIconSize(QSize(80, 80))
        self.carSpot_13.setCheckable(True)
        self.carSpot_13.setChecked(False)
        self.carSpot_13.setAutoExclusive(False)
        self.carSpot_13.setAutoDefault(False)
        self.carSpot_13.setFlat(False)

        self.gridLayout_3.addWidget(self.carSpot_13, 8, 0, 1, 1)

        self.carSpot_11 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_11.setObjectName(u"carSpot_11")
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.Button, brush)
        palette13.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_11.setPalette(palette13)
        self.carSpot_11.setMouseTracking(False)
        self.carSpot_11.setAutoFillBackground(False)
        self.carSpot_11.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_11.setIcon(icon1)
        self.carSpot_11.setIconSize(QSize(80, 80))
        self.carSpot_11.setCheckable(True)
        self.carSpot_11.setChecked(False)
        self.carSpot_11.setAutoExclusive(False)
        self.carSpot_11.setAutoDefault(False)
        self.carSpot_11.setFlat(False)

        self.gridLayout_3.addWidget(self.carSpot_11, 4, 0, 1, 1)

        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_3.addItem(self.horizontalSpacer_6, 5, 0, 1, 1)

        self.carSpot_12 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_12.setObjectName(u"carSpot_12")
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.Button, brush)
        palette14.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_12.setPalette(palette14)
        self.carSpot_12.setMouseTracking(False)
        self.carSpot_12.setAutoFillBackground(False)
        self.carSpot_12.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_12.setIcon(icon1)
        self.carSpot_12.setIconSize(QSize(80, 80))
        self.carSpot_12.setCheckable(True)
        self.carSpot_12.setChecked(False)
        self.carSpot_12.setAutoExclusive(False)
        self.carSpot_12.setAutoDefault(False)
        self.carSpot_12.setFlat(False)

        self.gridLayout_3.addWidget(self.carSpot_12, 2, 0, 1, 1)


        self.formLayout_2.setLayout(0, QFormLayout.LabelRole, self.gridLayout_3)

        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setSizeConstraint(QLayout.SizeConstraint.SetFixedSize)
        self.carSpot_16 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_16.setObjectName(u"carSpot_16")
        self.carSpot_16.setEnabled(True)
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.Button, brush)
        palette15.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_16.setPalette(palette15)
        self.carSpot_16.setMouseTracking(False)
        self.carSpot_16.setAutoFillBackground(False)
        self.carSpot_16.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_16.setIcon(icon1)
        self.carSpot_16.setIconSize(QSize(80, 80))
        self.carSpot_16.setCheckable(True)
        self.carSpot_16.setChecked(False)
        self.carSpot_16.setAutoExclusive(False)
        self.carSpot_16.setAutoDefault(False)
        self.carSpot_16.setFlat(False)

        self.gridLayout_4.addWidget(self.carSpot_16, 5, 0, 1, 1)

        self.carSpot_20 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_20.setObjectName(u"carSpot_20")
        self.carSpot_20.setEnabled(True)
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.Button, brush)
        palette16.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_20.setPalette(palette16)
        self.carSpot_20.setMouseTracking(False)
        self.carSpot_20.setAutoFillBackground(False)
        self.carSpot_20.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_20.setIcon(icon1)
        self.carSpot_20.setIconSize(QSize(80, 80))
        self.carSpot_20.setCheckable(True)
        self.carSpot_20.setChecked(False)
        self.carSpot_20.setAutoExclusive(False)
        self.carSpot_20.setAutoDefault(False)
        self.carSpot_20.setFlat(False)

        self.gridLayout_4.addWidget(self.carSpot_20, 1, 0, 1, 1)

        self.horizontalSpacer_15 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_15, 2, 0, 1, 1)

        self.carSpot_18 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_18.setObjectName(u"carSpot_18")
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.Button, brush)
        palette17.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_18.setPalette(palette17)
        self.carSpot_18.setMouseTracking(False)
        self.carSpot_18.setAutoFillBackground(False)
        self.carSpot_18.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_18.setIcon(icon1)
        self.carSpot_18.setIconSize(QSize(80, 80))
        self.carSpot_18.setCheckable(True)
        self.carSpot_18.setChecked(False)
        self.carSpot_18.setAutoExclusive(False)
        self.carSpot_18.setAutoDefault(False)
        self.carSpot_18.setFlat(False)

        self.gridLayout_4.addWidget(self.carSpot_18, 7, 0, 1, 1)

        self.horizontalSpacer_16 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_16, 8, 0, 1, 1)

        self.carSpot_17 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_17.setObjectName(u"carSpot_17")
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.Button, brush)
        palette18.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_17.setPalette(palette18)
        self.carSpot_17.setMouseTracking(False)
        self.carSpot_17.setAutoFillBackground(False)
        self.carSpot_17.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_17.setIcon(icon1)
        self.carSpot_17.setIconSize(QSize(80, 80))
        self.carSpot_17.setCheckable(True)
        self.carSpot_17.setChecked(False)
        self.carSpot_17.setAutoExclusive(False)
        self.carSpot_17.setAutoDefault(False)
        self.carSpot_17.setFlat(False)

        self.gridLayout_4.addWidget(self.carSpot_17, 3, 0, 1, 1)

        self.carSpot_19 = QPushButton(self.formLayoutWidget_2)
        self.carSpot_19.setObjectName(u"carSpot_19")
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.Button, brush)
        palette19.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette19.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette19.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        palette19.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        self.carSpot_19.setPalette(palette19)
        self.carSpot_19.setMouseTracking(False)
        self.carSpot_19.setAutoFillBackground(False)
        self.carSpot_19.setStyleSheet(u"QPushButton:disabled {\n"
"    background-color: red;\n"
"}")
        self.carSpot_19.setIcon(icon1)
        self.carSpot_19.setIconSize(QSize(80, 80))
        self.carSpot_19.setCheckable(True)
        self.carSpot_19.setChecked(False)
        self.carSpot_19.setAutoExclusive(False)
        self.carSpot_19.setAutoDefault(False)
        self.carSpot_19.setFlat(False)

        self.gridLayout_4.addWidget(self.carSpot_19, 9, 0, 1, 1)

        self.horizontalSpacer_14 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_14, 6, 0, 1, 1)

        self.horizontalSpacer_13 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_13, 4, 0, 1, 1)


        self.formLayout_2.setLayout(0, QFormLayout.FieldRole, self.gridLayout_4)

        self.confirmSpot = QPushButton(Widget)
        self.confirmSpot.setObjectName(u"confirmSpot")
        self.confirmSpot.setGeometry(QRect(550, 10, 151, 61))
        self.confirmSpot.setAutoRepeat(False)
        self.Warning1 = QDockWidget(Widget)
        self.Warning1.setObjectName(u"Warning1")
        self.Warning1.setGeometry(QRect(290, 380, 261, 171))
        self.Warning1.setAutoFillBackground(True)
        self.Warning1.setFloating(True)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.textEdit = QTextEdit(self.dockWidgetContents_2)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(20, 10, 231, 61))
        self.warning1Okay = QPushButton(self.dockWidgetContents_2)
        self.warning1Okay.setObjectName(u"warning1Okay")
        self.warning1Okay.setGeometry(QRect(80, 100, 93, 29))
        self.warning1Okay.setAutoRepeat(False)
        self.Warning1.setWidget(self.dockWidgetContents_2)
        self.reserveSpot = QDockWidget(Widget)
        self.reserveSpot.setObjectName(u"reserveSpot")
        self.reserveSpot.setGeometry(QRect(260, 100, 311, 261))
        palette20 = QPalette()
        self.reserveSpot.setPalette(palette20)
        self.reserveSpot.setAutoFillBackground(False)
        self.reserveSpot.setStyleSheet(u"")
        self.reserveSpot.setFloating(True)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.reserveButton = QPushButton(self.dockWidgetContents)
        self.reserveButton.setObjectName(u"reserveButton")
        self.reserveButton.setEnabled(True)
        self.reserveButton.setGeometry(QRect(20, 170, 111, 41))
        self.cancelButton = QPushButton(self.dockWidgetContents)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(190, 170, 111, 41))
        self.cancelButton.setAutoFillBackground(True)
        self.cancelButton.setCheckable(False)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setFlat(False)
        self.textEdit_3 = QTextEdit(self.dockWidgetContents)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(20, 10, 281, 141))
        self.reserveSpot.setWidget(self.dockWidgetContents)
        self.Warning2 = QDockWidget(Widget)
        self.Warning2.setObjectName(u"Warning2")
        self.Warning2.setGeometry(QRect(290, 560, 261, 171))
        self.Warning2.setFloating(True)
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        self.textEdit_2 = QTextEdit(self.dockWidgetContents_3)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(20, 10, 231, 61))
        self.warning1Okay_2 = QPushButton(self.dockWidgetContents_3)
        self.warning1Okay_2.setObjectName(u"warning1Okay_2")
        self.warning1Okay_2.setGeometry(QRect(80, 100, 93, 29))
        self.warning1Okay_2.setAutoRepeat(False)
        self.Warning2.setWidget(self.dockWidgetContents_3)

        self.retranslateUi(Widget)

        self.carSpot_1.setDefault(False)
        self.carSpot_5.setDefault(False)
        self.carSpot_3.setDefault(False)
        self.carSpot_4.setDefault(False)
        self.carSpot_2.setDefault(False)
        self.carSpot_6.setDefault(False)
        self.carSpot_10.setDefault(False)
        self.carSpot_7.setDefault(False)
        self.carSpot_8.setDefault(False)
        self.carSpot_9.setDefault(False)
        self.carSpot_15.setDefault(False)
        self.carSpot_14.setDefault(False)
        self.carSpot_13.setDefault(False)
        self.carSpot_11.setDefault(False)
        self.carSpot_12.setDefault(False)
        self.carSpot_16.setDefault(False)
        self.carSpot_20.setDefault(False)
        self.carSpot_18.setDefault(False)
        self.carSpot_17.setDefault(False)
        self.carSpot_19.setDefault(False)
        self.warning1Okay.setDefault(False)
        self.cancelButton.setDefault(False)
        self.warning1Okay_2.setDefault(False)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.carSpot_1.setText("")
        self.carSpot_5.setText("")
        self.carSpot_3.setText("")
        self.carSpot_4.setText("")
        self.carSpot_2.setText("")
        self.carSpot_6.setText("")
        self.carSpot_10.setText("")
        self.carSpot_7.setText("")
        self.carSpot_8.setText("")
        self.carSpot_9.setText("")
        self.carSpot_15.setText("")
        self.carSpot_14.setText("")
        self.carSpot_13.setText("")
        self.carSpot_11.setText("")
        self.carSpot_12.setText("")
        self.carSpot_16.setText("")
        self.carSpot_20.setText("")
        self.carSpot_18.setText("")
        self.carSpot_17.setText("")
        self.carSpot_19.setText("")
        self.confirmSpot.setText(QCoreApplication.translate("Widget", u"Confirm Spot", None))
        self.textEdit.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700;\">WARNING!<br />Please select only one spot</span></p></body></html>", None))
        self.warning1Okay.setText(QCoreApplication.translate("Widget", u"OKAY", None))
        self.reserveButton.setText(QCoreApplication.translate("Widget", u"Reserve", None))
        self.cancelButton.setText(QCoreApplication.translate("Widget", u"Cancel", None))
        self.textEdit_3.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:700;\">Do you want to reserve and continue to payment?</span></p></body></html>", None))
        self.textEdit_2.setHtml(QCoreApplication.translate("Widget", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700;\">WARNING!<br />Please select one spot</span></p></body></html>", None))
        self.warning1Okay_2.setText(QCoreApplication.translate("Widget", u"OKAY", None))
    # retranslateUi

